# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  workflow_dispatch:

name: Deploy to GitHub Pages

jobs:
  cleanup:
    name: 🧼 Clean up environment
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Delete previous deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  build:
    name: Build site
    needs: cleanup
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render all Rmd files
        run: lapply(list.files("site", ".*[.]Rmd$", full.names = TRUE), rmarkdown::render)
        shell: Rscript {0}

  deploy:
    name: Deploy to GitHub pages 🚀
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: site
