# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  workflow_dispatch:

name: Deploy to GitHub Pages

jobs:
  cleanup:
    name: 🧼 Clean up environment
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Delete previous deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true


  list-rmd:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(ls site/*.Rmd | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build:
    name: Build site
    needs: [cleanup, list-rmd]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rmd: ${{ fromJson(needs.list-rmd.outputs.matrix) }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: List files in repository
        run: |
          find ${{ github.workspace }} -type d -name '.*' -prune -o -print

      - name: Render all Rmd files
        run: rmarkdown::render("${{ matrix.rmd }}")
        shell: Rscript {0}

      - uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: |
            site/**/*.html
            site/**/*.pdf

  deploy:
    name: Deploy to GitHub pages 🚀
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        id: download
        with:
          name: build-result
          path: html

      - name: List files in repository
        run: |
          find ${{ github.workspace }} -type d -name '.*' -prune -o -print

      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean-exclude: ${{ steps.download.outputs.download-path }}
          branch: gh-pages
          folder: ${{ steps.download.outputs.download-path }}

      - name: List files after build
        run: |
          find ${{ github.workspace }} -type d -name '.*' -prune -o -print
